fix add radio/checkbox input  multiple (with options config fields)
novius-os/fuelphp-core pull request #7
Opened 2017-02-09 10:52 UTC by cholletNovius

debug viewtemplate when we want add field radio or checkbox mulitple options

2017-02-09 11:04 UTC, Meroje requested changes
You replaced tabs with spaces and now the diff is all messed up and hard to follow

2017-02-09 11:17 UTC, cholletNovius commented on classes/fieldset/field.php
> +            $label = $form->label($labelName, null, array('id' => 'label_'.$this->name));
exemple of field config : 

``` 'prof_type' => array( 
         'label' => __('Je suis').'<span class="required">*</span>',
            'form' => array(
                'type' => 'radio',
                'value' => 'journaliste',
                'options' => array(
                    'journaliste' => __('Journaliste'),
                    'pro' => __('Professionnel'),
                ),
            ),
            'validation' => array('required'),
        ),```

when we are `validation`, `$this->label` is an array.

2017-02-09 11:21 UTC, cholletNovius commented on classes/fieldset/field.php
> +            $buildFieldMap = array_map(function($value, $key) {
When radio/checkbox field is multiple like :
```
'form' => array(
                'type' => 'radio',
                'value' => 'journaliste',
                'options' => array(
                    'journaliste' => __('Journaliste'),
                    'pro' => __('Professionnel'),
                ),
            ),
```
'$build_field' is array with `'label display' => 'value input display'`
But there was no label for each input display.

2017-02-09 11:30 UTC, Meroje approved these changes

2017-02-09 14:36 UTC, cholletNovius commented
up

2017-02-09 14:39 UTC, Meroje commented
:+1: works for me

2017-02-10 10:23 UTC, jguyomard approved these changes

2017-02-14 15:59 UTC, merged